version: '3'

vars:
  VERSION: '{{ default "swov1" .VERSION }}'

tasks:
  generate:
    cmds:
      - for f in `cat {{ .VERSION }}/.openapi-generator/FILES`; do rm -f {{ .VERSION }}/$f; done
      - docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v7.7.0 generate -g go -i /local/{{ .VERSION }}/openapi.json -c /local/{{ .VERSION }}/.openapi-generator-config.yml -o local/{{ .VERSION }}