/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckForString type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckForString{}

// CheckForString struct for CheckForString
type CheckForString struct {
	Type string `json:"type"`
	Status string `json:"status"`
	String string `json:"string"`
}

type _CheckForString CheckForString

// NewCheckForString instantiates a new CheckForString object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckForString(type_ string, status string, string_ string) *CheckForString {
	this := CheckForString{}
	this.Type = type_
	this.Status = status
	this.String = string_
	return &this
}

// NewCheckForStringWithDefaults instantiates a new CheckForString object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckForStringWithDefaults() *CheckForString {
	this := CheckForString{}
	return &this
}

// GetType returns the Type field value
func (o *CheckForString) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CheckForString) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CheckForString) SetType(v string) {
	o.Type = v
}

// GetStatus returns the Status field value
func (o *CheckForString) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CheckForString) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CheckForString) SetStatus(v string) {
	o.Status = v
}

// GetString returns the String field value
func (o *CheckForString) GetString() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.String
}

// GetStringOk returns a tuple with the String field value
// and a boolean to check if the value has been set.
func (o *CheckForString) GetStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.String, true
}

// SetString sets field value
func (o *CheckForString) SetString(v string) {
	o.String = v
}

func (o CheckForString) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckForString) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["status"] = o.Status
	toSerialize["string"] = o.String
	return toSerialize, nil
}

func (o *CheckForString) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"status",
		"string",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckForString := _CheckForString{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckForString)

	if err != nil {
		return err
	}

	*o = CheckForString(varCheckForString)

	return err
}

type NullableCheckForString struct {
	value *CheckForString
	isSet bool
}

func (v NullableCheckForString) Get() *CheckForString {
	return v.value
}

func (v *NullableCheckForString) Set(val *CheckForString) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckForString) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckForString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckForString(val *CheckForString) *NullableCheckForString {
	return &NullableCheckForString{value: val, isSet: true}
}

func (v NullableCheckForString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckForString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


