/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HttpMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttpMessage{}

// HttpMessage struct for HttpMessage
type HttpMessage struct {
	DurationInMs int32 `json:"durationInMs"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	Headers []HttpHeader `json:"headers"`
	Body *string `json:"body,omitempty"`
}

type _HttpMessage HttpMessage

// NewHttpMessage instantiates a new HttpMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpMessage(durationInMs int32, headers []HttpHeader) *HttpMessage {
	this := HttpMessage{}
	this.DurationInMs = durationInMs
	this.Headers = headers
	return &this
}

// NewHttpMessageWithDefaults instantiates a new HttpMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpMessageWithDefaults() *HttpMessage {
	this := HttpMessage{}
	return &this
}

// GetDurationInMs returns the DurationInMs field value
func (o *HttpMessage) GetDurationInMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationInMs
}

// GetDurationInMsOk returns a tuple with the DurationInMs field value
// and a boolean to check if the value has been set.
func (o *HttpMessage) GetDurationInMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationInMs, true
}

// SetDurationInMs sets field value
func (o *HttpMessage) SetDurationInMs(v int32) {
	o.DurationInMs = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *HttpMessage) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpMessage) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *HttpMessage) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *HttpMessage) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetHeaders returns the Headers field value
func (o *HttpMessage) GetHeaders() []HttpHeader {
	if o == nil {
		var ret []HttpHeader
		return ret
	}

	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value
// and a boolean to check if the value has been set.
func (o *HttpMessage) GetHeadersOk() ([]HttpHeader, bool) {
	if o == nil {
		return nil, false
	}
	return o.Headers, true
}

// SetHeaders sets field value
func (o *HttpMessage) SetHeaders(v []HttpHeader) {
	o.Headers = v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *HttpMessage) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpMessage) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *HttpMessage) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *HttpMessage) SetBody(v string) {
	o.Body = &v
}

func (o HttpMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["durationInMs"] = o.DurationInMs
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	toSerialize["headers"] = o.Headers
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	return toSerialize, nil
}

func (o *HttpMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"durationInMs",
		"headers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHttpMessage := _HttpMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHttpMessage)

	if err != nil {
		return err
	}

	*o = HttpMessage(varHttpMessage)

	return err
}

type NullableHttpMessage struct {
	value *HttpMessage
	isSet bool
}

func (v NullableHttpMessage) Get() *HttpMessage {
	return v.value
}

func (v *NullableHttpMessage) Set(val *HttpMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpMessage(val *HttpMessage) *NullableHttpMessage {
	return &NullableHttpMessage{value: val, isSet: true}
}

func (v NullableHttpMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


