/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntityIdSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityIdSchema{}

// EntityIdSchema struct for EntityIdSchema
type EntityIdSchema struct {
	Id string `json:"id"`
}

type _EntityIdSchema EntityIdSchema

// NewEntityIdSchema instantiates a new EntityIdSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityIdSchema(id string) *EntityIdSchema {
	this := EntityIdSchema{}
	this.Id = id
	return &this
}

// NewEntityIdSchemaWithDefaults instantiates a new EntityIdSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityIdSchemaWithDefaults() *EntityIdSchema {
	this := EntityIdSchema{}
	return &this
}

// GetId returns the Id field value
func (o *EntityIdSchema) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EntityIdSchema) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EntityIdSchema) SetId(v string) {
	o.Id = v
}

func (o EntityIdSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityIdSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *EntityIdSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityIdSchema := _EntityIdSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntityIdSchema)

	if err != nil {
		return err
	}

	*o = EntityIdSchema(varEntityIdSchema)

	return err
}

type NullableEntityIdSchema struct {
	value *EntityIdSchema
	isSet bool
}

func (v NullableEntityIdSchema) Get() *EntityIdSchema {
	return v.value
}

func (v *NullableEntityIdSchema) Set(val *EntityIdSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityIdSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityIdSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityIdSchema(val *EntityIdSchema) *NullableEntityIdSchema {
	return &NullableEntityIdSchema{value: val, isSet: true}
}

func (v NullableEntityIdSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityIdSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


