/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListMetricsForEntityTypeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMetricsForEntityTypeResponse{}

// ListMetricsForEntityTypeResponse struct for ListMetricsForEntityTypeResponse
type ListMetricsForEntityTypeResponse struct {
	Type string `json:"type"`
	Metrics []GetMetricResponse `json:"metrics"`
}

type _ListMetricsForEntityTypeResponse ListMetricsForEntityTypeResponse

// NewListMetricsForEntityTypeResponse instantiates a new ListMetricsForEntityTypeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMetricsForEntityTypeResponse(type_ string, metrics []GetMetricResponse) *ListMetricsForEntityTypeResponse {
	this := ListMetricsForEntityTypeResponse{}
	this.Type = type_
	this.Metrics = metrics
	return &this
}

// NewListMetricsForEntityTypeResponseWithDefaults instantiates a new ListMetricsForEntityTypeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMetricsForEntityTypeResponseWithDefaults() *ListMetricsForEntityTypeResponse {
	this := ListMetricsForEntityTypeResponse{}
	return &this
}

// GetType returns the Type field value
func (o *ListMetricsForEntityTypeResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ListMetricsForEntityTypeResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ListMetricsForEntityTypeResponse) SetType(v string) {
	o.Type = v
}

// GetMetrics returns the Metrics field value
func (o *ListMetricsForEntityTypeResponse) GetMetrics() []GetMetricResponse {
	if o == nil {
		var ret []GetMetricResponse
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *ListMetricsForEntityTypeResponse) GetMetricsOk() ([]GetMetricResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Metrics, true
}

// SetMetrics sets field value
func (o *ListMetricsForEntityTypeResponse) SetMetrics(v []GetMetricResponse) {
	o.Metrics = v
}

func (o ListMetricsForEntityTypeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMetricsForEntityTypeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["metrics"] = o.Metrics
	return toSerialize, nil
}

func (o *ListMetricsForEntityTypeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"metrics",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMetricsForEntityTypeResponse := _ListMetricsForEntityTypeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListMetricsForEntityTypeResponse)

	if err != nil {
		return err
	}

	*o = ListMetricsForEntityTypeResponse(varListMetricsForEntityTypeResponse)

	return err
}

type NullableListMetricsForEntityTypeResponse struct {
	value *ListMetricsForEntityTypeResponse
	isSet bool
}

func (v NullableListMetricsForEntityTypeResponse) Get() *ListMetricsForEntityTypeResponse {
	return v.value
}

func (v *NullableListMetricsForEntityTypeResponse) Set(val *ListMetricsForEntityTypeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListMetricsForEntityTypeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListMetricsForEntityTypeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMetricsForEntityTypeResponse(val *ListMetricsForEntityTypeResponse) *NullableListMetricsForEntityTypeResponse {
	return &NullableListMetricsForEntityTypeResponse{value: val, isSet: true}
}

func (v NullableListMetricsForEntityTypeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMetricsForEntityTypeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


