/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InnerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InnerError{}

// InnerError An object containing more specific information than the current object about the error.
type InnerError struct {
	// A more specific error code than was provided by the containing error.
	Code string `json:"code"`
	// A human-readable representation of the error.
	Message *string `json:"message,omitempty"`
	// The target of the error.
	Target *string `json:"target,omitempty"`
	Innererror *InnerError `json:"innererror,omitempty"`
}

type _InnerError InnerError

// NewInnerError instantiates a new InnerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInnerError(code string) *InnerError {
	this := InnerError{}
	this.Code = code
	return &this
}

// NewInnerErrorWithDefaults instantiates a new InnerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInnerErrorWithDefaults() *InnerError {
	this := InnerError{}
	return &this
}

// GetCode returns the Code field value
func (o *InnerError) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *InnerError) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *InnerError) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *InnerError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InnerError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *InnerError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *InnerError) SetMessage(v string) {
	o.Message = &v
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *InnerError) GetTarget() string {
	if o == nil || IsNil(o.Target) {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InnerError) GetTargetOk() (*string, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *InnerError) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *InnerError) SetTarget(v string) {
	o.Target = &v
}

// GetInnererror returns the Innererror field value if set, zero value otherwise.
func (o *InnerError) GetInnererror() InnerError {
	if o == nil || IsNil(o.Innererror) {
		var ret InnerError
		return ret
	}
	return *o.Innererror
}

// GetInnererrorOk returns a tuple with the Innererror field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InnerError) GetInnererrorOk() (*InnerError, bool) {
	if o == nil || IsNil(o.Innererror) {
		return nil, false
	}
	return o.Innererror, true
}

// HasInnererror returns a boolean if a field has been set.
func (o *InnerError) HasInnererror() bool {
	if o != nil && !IsNil(o.Innererror) {
		return true
	}

	return false
}

// SetInnererror gets a reference to the given InnerError and assigns it to the Innererror field.
func (o *InnerError) SetInnererror(v InnerError) {
	o.Innererror = &v
}

func (o InnerError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InnerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}
	if !IsNil(o.Innererror) {
		toSerialize["innererror"] = o.Innererror
	}
	return toSerialize, nil
}

func (o *InnerError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInnerError := _InnerError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInnerError)

	if err != nil {
		return err
	}

	*o = InnerError(varInnerError)

	return err
}

type NullableInnerError struct {
	value *InnerError
	isSet bool
}

func (v NullableInnerError) Get() *InnerError {
	return v.value
}

func (v *NullableInnerError) Set(val *InnerError) {
	v.value = val
	v.isSet = true
}

func (v NullableInnerError) IsSet() bool {
	return v.isSet
}

func (v *NullableInnerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInnerError(val *InnerError) *NullableInnerError {
	return &NullableInnerError{value: val, isSet: true}
}

func (v NullableInnerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInnerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


