/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SslCertificate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SslCertificate{}

// SslCertificate struct for SslCertificate
type SslCertificate struct {
	Name string `json:"name"`
	ValidTo string `json:"validTo"`
	Certificate string `json:"certificate"`
}

type _SslCertificate SslCertificate

// NewSslCertificate instantiates a new SslCertificate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSslCertificate(name string, validTo string, certificate string) *SslCertificate {
	this := SslCertificate{}
	this.Name = name
	this.ValidTo = validTo
	this.Certificate = certificate
	return &this
}

// NewSslCertificateWithDefaults instantiates a new SslCertificate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSslCertificateWithDefaults() *SslCertificate {
	this := SslCertificate{}
	return &this
}

// GetName returns the Name field value
func (o *SslCertificate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SslCertificate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SslCertificate) SetName(v string) {
	o.Name = v
}

// GetValidTo returns the ValidTo field value
func (o *SslCertificate) GetValidTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValidTo
}

// GetValidToOk returns a tuple with the ValidTo field value
// and a boolean to check if the value has been set.
func (o *SslCertificate) GetValidToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidTo, true
}

// SetValidTo sets field value
func (o *SslCertificate) SetValidTo(v string) {
	o.ValidTo = v
}

// GetCertificate returns the Certificate field value
func (o *SslCertificate) GetCertificate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value
// and a boolean to check if the value has been set.
func (o *SslCertificate) GetCertificateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Certificate, true
}

// SetCertificate sets field value
func (o *SslCertificate) SetCertificate(v string) {
	o.Certificate = v
}

func (o SslCertificate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SslCertificate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["validTo"] = o.ValidTo
	toSerialize["certificate"] = o.Certificate
	return toSerialize, nil
}

func (o *SslCertificate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"validTo",
		"certificate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSslCertificate := _SslCertificate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSslCertificate)

	if err != nil {
		return err
	}

	*o = SslCertificate(varSslCertificate)

	return err
}

type NullableSslCertificate struct {
	value *SslCertificate
	isSet bool
}

func (v NullableSslCertificate) Get() *SslCertificate {
	return v.value
}

func (v *NullableSslCertificate) Set(val *SslCertificate) {
	v.value = val
	v.isSet = true
}

func (v NullableSslCertificate) IsSet() bool {
	return v.isSet
}

func (v *NullableSslCertificate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSslCertificate(val *SslCertificate) *NullableSslCertificate {
	return &NullableSslCertificate{value: val, isSet: true}
}

func (v NullableSslCertificate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSslCertificate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


