/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnalysisSchemaAllOfOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalysisSchemaAllOfOutput{}

// AnalysisSchemaAllOfOutput struct for AnalysisSchemaAllOfOutput
type AnalysisSchemaAllOfOutput struct {
	DurationInMs int32 `json:"durationInMs"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	RawOutput string `json:"rawOutput"`
}

type _AnalysisSchemaAllOfOutput AnalysisSchemaAllOfOutput

// NewAnalysisSchemaAllOfOutput instantiates a new AnalysisSchemaAllOfOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalysisSchemaAllOfOutput(durationInMs int32, rawOutput string) *AnalysisSchemaAllOfOutput {
	this := AnalysisSchemaAllOfOutput{}
	this.DurationInMs = durationInMs
	this.RawOutput = rawOutput
	return &this
}

// NewAnalysisSchemaAllOfOutputWithDefaults instantiates a new AnalysisSchemaAllOfOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalysisSchemaAllOfOutputWithDefaults() *AnalysisSchemaAllOfOutput {
	this := AnalysisSchemaAllOfOutput{}
	return &this
}

// GetDurationInMs returns the DurationInMs field value
func (o *AnalysisSchemaAllOfOutput) GetDurationInMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationInMs
}

// GetDurationInMsOk returns a tuple with the DurationInMs field value
// and a boolean to check if the value has been set.
func (o *AnalysisSchemaAllOfOutput) GetDurationInMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationInMs, true
}

// SetDurationInMs sets field value
func (o *AnalysisSchemaAllOfOutput) SetDurationInMs(v int32) {
	o.DurationInMs = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *AnalysisSchemaAllOfOutput) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisSchemaAllOfOutput) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *AnalysisSchemaAllOfOutput) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *AnalysisSchemaAllOfOutput) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetRawOutput returns the RawOutput field value
func (o *AnalysisSchemaAllOfOutput) GetRawOutput() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RawOutput
}

// GetRawOutputOk returns a tuple with the RawOutput field value
// and a boolean to check if the value has been set.
func (o *AnalysisSchemaAllOfOutput) GetRawOutputOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RawOutput, true
}

// SetRawOutput sets field value
func (o *AnalysisSchemaAllOfOutput) SetRawOutput(v string) {
	o.RawOutput = v
}

func (o AnalysisSchemaAllOfOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalysisSchemaAllOfOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["durationInMs"] = o.DurationInMs
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	toSerialize["rawOutput"] = o.RawOutput
	return toSerialize, nil
}

func (o *AnalysisSchemaAllOfOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"durationInMs",
		"rawOutput",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnalysisSchemaAllOfOutput := _AnalysisSchemaAllOfOutput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnalysisSchemaAllOfOutput)

	if err != nil {
		return err
	}

	*o = AnalysisSchemaAllOfOutput(varAnalysisSchemaAllOfOutput)

	return err
}

type NullableAnalysisSchemaAllOfOutput struct {
	value *AnalysisSchemaAllOfOutput
	isSet bool
}

func (v NullableAnalysisSchemaAllOfOutput) Get() *AnalysisSchemaAllOfOutput {
	return v.value
}

func (v *NullableAnalysisSchemaAllOfOutput) Set(val *AnalysisSchemaAllOfOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalysisSchemaAllOfOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalysisSchemaAllOfOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalysisSchemaAllOfOutput(val *AnalysisSchemaAllOfOutput) *NullableAnalysisSchemaAllOfOutput {
	return &NullableAnalysisSchemaAllOfOutput{value: val, isSet: true}
}

func (v NullableAnalysisSchemaAllOfOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalysisSchemaAllOfOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


