/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
)

// checks if the NextOnDemandAvailabilityTime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NextOnDemandAvailabilityTime{}

// NextOnDemandAvailabilityTime struct for NextOnDemandAvailabilityTime
type NextOnDemandAvailabilityTime struct {
	// Timestamp for when the next on-demand check could be executed.  If at \"0\", it means you can execute it anytime. 
	NextOnDemandAvailabilityTime *float32 `json:"nextOnDemandAvailabilityTime,omitempty"`
}

// NewNextOnDemandAvailabilityTime instantiates a new NextOnDemandAvailabilityTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNextOnDemandAvailabilityTime() *NextOnDemandAvailabilityTime {
	this := NextOnDemandAvailabilityTime{}
	return &this
}

// NewNextOnDemandAvailabilityTimeWithDefaults instantiates a new NextOnDemandAvailabilityTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNextOnDemandAvailabilityTimeWithDefaults() *NextOnDemandAvailabilityTime {
	this := NextOnDemandAvailabilityTime{}
	return &this
}

// GetNextOnDemandAvailabilityTime returns the NextOnDemandAvailabilityTime field value if set, zero value otherwise.
func (o *NextOnDemandAvailabilityTime) GetNextOnDemandAvailabilityTime() float32 {
	if o == nil || IsNil(o.NextOnDemandAvailabilityTime) {
		var ret float32
		return ret
	}
	return *o.NextOnDemandAvailabilityTime
}

// GetNextOnDemandAvailabilityTimeOk returns a tuple with the NextOnDemandAvailabilityTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NextOnDemandAvailabilityTime) GetNextOnDemandAvailabilityTimeOk() (*float32, bool) {
	if o == nil || IsNil(o.NextOnDemandAvailabilityTime) {
		return nil, false
	}
	return o.NextOnDemandAvailabilityTime, true
}

// HasNextOnDemandAvailabilityTime returns a boolean if a field has been set.
func (o *NextOnDemandAvailabilityTime) HasNextOnDemandAvailabilityTime() bool {
	if o != nil && !IsNil(o.NextOnDemandAvailabilityTime) {
		return true
	}

	return false
}

// SetNextOnDemandAvailabilityTime gets a reference to the given float32 and assigns it to the NextOnDemandAvailabilityTime field.
func (o *NextOnDemandAvailabilityTime) SetNextOnDemandAvailabilityTime(v float32) {
	o.NextOnDemandAvailabilityTime = &v
}

func (o NextOnDemandAvailabilityTime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NextOnDemandAvailabilityTime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextOnDemandAvailabilityTime) {
		toSerialize["nextOnDemandAvailabilityTime"] = o.NextOnDemandAvailabilityTime
	}
	return toSerialize, nil
}

type NullableNextOnDemandAvailabilityTime struct {
	value *NextOnDemandAvailabilityTime
	isSet bool
}

func (v NullableNextOnDemandAvailabilityTime) Get() *NextOnDemandAvailabilityTime {
	return v.value
}

func (v *NullableNextOnDemandAvailabilityTime) Set(val *NextOnDemandAvailabilityTime) {
	v.value = val
	v.isSet = true
}

func (v NullableNextOnDemandAvailabilityTime) IsSet() bool {
	return v.isSet
}

func (v *NullableNextOnDemandAvailabilityTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNextOnDemandAvailabilityTime(val *NextOnDemandAvailabilityTime) *NullableNextOnDemandAvailabilityTime {
	return &NullableNextOnDemandAvailabilityTime{value: val, isSet: true}
}

func (v NullableNextOnDemandAvailabilityTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNextOnDemandAvailabilityTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


