/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnalysisDetailsBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalysisDetailsBase{}

// AnalysisDetailsBase struct for AnalysisDetailsBase
type AnalysisDetailsBase struct {
	DurationInMs int32 `json:"durationInMs"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

type _AnalysisDetailsBase AnalysisDetailsBase

// NewAnalysisDetailsBase instantiates a new AnalysisDetailsBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalysisDetailsBase(durationInMs int32) *AnalysisDetailsBase {
	this := AnalysisDetailsBase{}
	this.DurationInMs = durationInMs
	return &this
}

// NewAnalysisDetailsBaseWithDefaults instantiates a new AnalysisDetailsBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalysisDetailsBaseWithDefaults() *AnalysisDetailsBase {
	this := AnalysisDetailsBase{}
	return &this
}

// GetDurationInMs returns the DurationInMs field value
func (o *AnalysisDetailsBase) GetDurationInMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationInMs
}

// GetDurationInMsOk returns a tuple with the DurationInMs field value
// and a boolean to check if the value has been set.
func (o *AnalysisDetailsBase) GetDurationInMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationInMs, true
}

// SetDurationInMs sets field value
func (o *AnalysisDetailsBase) SetDurationInMs(v int32) {
	o.DurationInMs = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *AnalysisDetailsBase) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisDetailsBase) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *AnalysisDetailsBase) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *AnalysisDetailsBase) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

func (o AnalysisDetailsBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalysisDetailsBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["durationInMs"] = o.DurationInMs
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	return toSerialize, nil
}

func (o *AnalysisDetailsBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"durationInMs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnalysisDetailsBase := _AnalysisDetailsBase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnalysisDetailsBase)

	if err != nil {
		return err
	}

	*o = AnalysisDetailsBase(varAnalysisDetailsBase)

	return err
}

type NullableAnalysisDetailsBase struct {
	value *AnalysisDetailsBase
	isSet bool
}

func (v NullableAnalysisDetailsBase) Get() *AnalysisDetailsBase {
	return v.value
}

func (v *NullableAnalysisDetailsBase) Set(val *AnalysisDetailsBase) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalysisDetailsBase) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalysisDetailsBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalysisDetailsBase(val *AnalysisDetailsBase) *NullableAnalysisDetailsBase {
	return &NullableAnalysisDetailsBase{value: val, isSet: true}
}

func (v NullableAnalysisDetailsBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalysisDetailsBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


