/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListMetricAttributeValuesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMetricAttributeValuesResponse{}

// ListMetricAttributeValuesResponse struct for ListMetricAttributeValuesResponse
type ListMetricAttributeValuesResponse struct {
	Name string `json:"name"`
	Values []string `json:"values"`
	PageInfo *PageInfo `json:"pageInfo,omitempty"`
}

type _ListMetricAttributeValuesResponse ListMetricAttributeValuesResponse

// NewListMetricAttributeValuesResponse instantiates a new ListMetricAttributeValuesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMetricAttributeValuesResponse(name string, values []string) *ListMetricAttributeValuesResponse {
	this := ListMetricAttributeValuesResponse{}
	this.Name = name
	this.Values = values
	return &this
}

// NewListMetricAttributeValuesResponseWithDefaults instantiates a new ListMetricAttributeValuesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMetricAttributeValuesResponseWithDefaults() *ListMetricAttributeValuesResponse {
	this := ListMetricAttributeValuesResponse{}
	return &this
}

// GetName returns the Name field value
func (o *ListMetricAttributeValuesResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListMetricAttributeValuesResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListMetricAttributeValuesResponse) SetName(v string) {
	o.Name = v
}

// GetValues returns the Values field value
func (o *ListMetricAttributeValuesResponse) GetValues() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *ListMetricAttributeValuesResponse) GetValuesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *ListMetricAttributeValuesResponse) SetValues(v []string) {
	o.Values = v
}

// GetPageInfo returns the PageInfo field value if set, zero value otherwise.
func (o *ListMetricAttributeValuesResponse) GetPageInfo() PageInfo {
	if o == nil || IsNil(o.PageInfo) {
		var ret PageInfo
		return ret
	}
	return *o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMetricAttributeValuesResponse) GetPageInfoOk() (*PageInfo, bool) {
	if o == nil || IsNil(o.PageInfo) {
		return nil, false
	}
	return o.PageInfo, true
}

// HasPageInfo returns a boolean if a field has been set.
func (o *ListMetricAttributeValuesResponse) HasPageInfo() bool {
	if o != nil && !IsNil(o.PageInfo) {
		return true
	}

	return false
}

// SetPageInfo gets a reference to the given PageInfo and assigns it to the PageInfo field.
func (o *ListMetricAttributeValuesResponse) SetPageInfo(v PageInfo) {
	o.PageInfo = &v
}

func (o ListMetricAttributeValuesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMetricAttributeValuesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["values"] = o.Values
	if !IsNil(o.PageInfo) {
		toSerialize["pageInfo"] = o.PageInfo
	}
	return toSerialize, nil
}

func (o *ListMetricAttributeValuesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"values",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMetricAttributeValuesResponse := _ListMetricAttributeValuesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListMetricAttributeValuesResponse)

	if err != nil {
		return err
	}

	*o = ListMetricAttributeValuesResponse(varListMetricAttributeValuesResponse)

	return err
}

type NullableListMetricAttributeValuesResponse struct {
	value *ListMetricAttributeValuesResponse
	isSet bool
}

func (v NullableListMetricAttributeValuesResponse) Get() *ListMetricAttributeValuesResponse {
	return v.value
}

func (v *NullableListMetricAttributeValuesResponse) Set(val *ListMetricAttributeValuesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListMetricAttributeValuesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListMetricAttributeValuesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMetricAttributeValuesResponse(val *ListMetricAttributeValuesResponse) *NullableListMetricAttributeValuesResponse {
	return &NullableListMetricAttributeValuesResponse{value: val, isSet: true}
}

func (v NullableListMetricAttributeValuesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMetricAttributeValuesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


