/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IpLookupDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpLookupDetails{}

// IpLookupDetails struct for IpLookupDetails
type IpLookupDetails struct {
	Hostname string `json:"hostname"`
	ResolvedIp string `json:"resolvedIp"`
}

type _IpLookupDetails IpLookupDetails

// NewIpLookupDetails instantiates a new IpLookupDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpLookupDetails(hostname string, resolvedIp string) *IpLookupDetails {
	this := IpLookupDetails{}
	this.Hostname = hostname
	this.ResolvedIp = resolvedIp
	return &this
}

// NewIpLookupDetailsWithDefaults instantiates a new IpLookupDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpLookupDetailsWithDefaults() *IpLookupDetails {
	this := IpLookupDetails{}
	return &this
}

// GetHostname returns the Hostname field value
func (o *IpLookupDetails) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *IpLookupDetails) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *IpLookupDetails) SetHostname(v string) {
	o.Hostname = v
}

// GetResolvedIp returns the ResolvedIp field value
func (o *IpLookupDetails) GetResolvedIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResolvedIp
}

// GetResolvedIpOk returns a tuple with the ResolvedIp field value
// and a boolean to check if the value has been set.
func (o *IpLookupDetails) GetResolvedIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResolvedIp, true
}

// SetResolvedIp sets field value
func (o *IpLookupDetails) SetResolvedIp(v string) {
	o.ResolvedIp = v
}

func (o IpLookupDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpLookupDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hostname"] = o.Hostname
	toSerialize["resolvedIp"] = o.ResolvedIp
	return toSerialize, nil
}

func (o *IpLookupDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hostname",
		"resolvedIp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIpLookupDetails := _IpLookupDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIpLookupDetails)

	if err != nil {
		return err
	}

	*o = IpLookupDetails(varIpLookupDetails)

	return err
}

type NullableIpLookupDetails struct {
	value *IpLookupDetails
	isSet bool
}

func (v NullableIpLookupDetails) Get() *IpLookupDetails {
	return v.value
}

func (v *NullableIpLookupDetails) Set(val *IpLookupDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableIpLookupDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableIpLookupDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpLookupDetails(val *IpLookupDetails) *NullableIpLookupDetails {
	return &NullableIpLookupDetails{value: val, isSet: true}
}

func (v NullableIpLookupDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpLookupDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


