/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnalysisSchemaAllOfIpLookupDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalysisSchemaAllOfIpLookupDetails{}

// AnalysisSchemaAllOfIpLookupDetails struct for AnalysisSchemaAllOfIpLookupDetails
type AnalysisSchemaAllOfIpLookupDetails struct {
	DurationInMs int32 `json:"durationInMs"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	Hostname string `json:"hostname"`
	ResolvedIp string `json:"resolvedIp"`
}

type _AnalysisSchemaAllOfIpLookupDetails AnalysisSchemaAllOfIpLookupDetails

// NewAnalysisSchemaAllOfIpLookupDetails instantiates a new AnalysisSchemaAllOfIpLookupDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalysisSchemaAllOfIpLookupDetails(durationInMs int32, hostname string, resolvedIp string) *AnalysisSchemaAllOfIpLookupDetails {
	this := AnalysisSchemaAllOfIpLookupDetails{}
	this.DurationInMs = durationInMs
	this.Hostname = hostname
	this.ResolvedIp = resolvedIp
	return &this
}

// NewAnalysisSchemaAllOfIpLookupDetailsWithDefaults instantiates a new AnalysisSchemaAllOfIpLookupDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalysisSchemaAllOfIpLookupDetailsWithDefaults() *AnalysisSchemaAllOfIpLookupDetails {
	this := AnalysisSchemaAllOfIpLookupDetails{}
	return &this
}

// GetDurationInMs returns the DurationInMs field value
func (o *AnalysisSchemaAllOfIpLookupDetails) GetDurationInMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationInMs
}

// GetDurationInMsOk returns a tuple with the DurationInMs field value
// and a boolean to check if the value has been set.
func (o *AnalysisSchemaAllOfIpLookupDetails) GetDurationInMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationInMs, true
}

// SetDurationInMs sets field value
func (o *AnalysisSchemaAllOfIpLookupDetails) SetDurationInMs(v int32) {
	o.DurationInMs = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *AnalysisSchemaAllOfIpLookupDetails) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisSchemaAllOfIpLookupDetails) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *AnalysisSchemaAllOfIpLookupDetails) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *AnalysisSchemaAllOfIpLookupDetails) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetHostname returns the Hostname field value
func (o *AnalysisSchemaAllOfIpLookupDetails) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *AnalysisSchemaAllOfIpLookupDetails) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *AnalysisSchemaAllOfIpLookupDetails) SetHostname(v string) {
	o.Hostname = v
}

// GetResolvedIp returns the ResolvedIp field value
func (o *AnalysisSchemaAllOfIpLookupDetails) GetResolvedIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResolvedIp
}

// GetResolvedIpOk returns a tuple with the ResolvedIp field value
// and a boolean to check if the value has been set.
func (o *AnalysisSchemaAllOfIpLookupDetails) GetResolvedIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResolvedIp, true
}

// SetResolvedIp sets field value
func (o *AnalysisSchemaAllOfIpLookupDetails) SetResolvedIp(v string) {
	o.ResolvedIp = v
}

func (o AnalysisSchemaAllOfIpLookupDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalysisSchemaAllOfIpLookupDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["durationInMs"] = o.DurationInMs
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	toSerialize["hostname"] = o.Hostname
	toSerialize["resolvedIp"] = o.ResolvedIp
	return toSerialize, nil
}

func (o *AnalysisSchemaAllOfIpLookupDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"durationInMs",
		"hostname",
		"resolvedIp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnalysisSchemaAllOfIpLookupDetails := _AnalysisSchemaAllOfIpLookupDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnalysisSchemaAllOfIpLookupDetails)

	if err != nil {
		return err
	}

	*o = AnalysisSchemaAllOfIpLookupDetails(varAnalysisSchemaAllOfIpLookupDetails)

	return err
}

type NullableAnalysisSchemaAllOfIpLookupDetails struct {
	value *AnalysisSchemaAllOfIpLookupDetails
	isSet bool
}

func (v NullableAnalysisSchemaAllOfIpLookupDetails) Get() *AnalysisSchemaAllOfIpLookupDetails {
	return v.value
}

func (v *NullableAnalysisSchemaAllOfIpLookupDetails) Set(val *AnalysisSchemaAllOfIpLookupDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalysisSchemaAllOfIpLookupDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalysisSchemaAllOfIpLookupDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalysisSchemaAllOfIpLookupDetails(val *AnalysisSchemaAllOfIpLookupDetails) *NullableAnalysisSchemaAllOfIpLookupDetails {
	return &NullableAnalysisSchemaAllOfIpLookupDetails{value: val, isSet: true}
}

func (v NullableAnalysisSchemaAllOfIpLookupDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalysisSchemaAllOfIpLookupDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


