/*
SolarWinds Observability REST API

[Rest API Documentation](https://documentation.solarwinds.com/en/success_center/observability/content/api/api-swagger.htm)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swov1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntityBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityBase{}

// EntityBase struct for EntityBase
type EntityBase struct {
	Id string `json:"id"`
	Type string `json:"type"`
}

type _EntityBase EntityBase

// NewEntityBase instantiates a new EntityBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityBase(id string, type_ string) *EntityBase {
	this := EntityBase{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewEntityBaseWithDefaults instantiates a new EntityBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityBaseWithDefaults() *EntityBase {
	this := EntityBase{}
	return &this
}

// GetId returns the Id field value
func (o *EntityBase) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EntityBase) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EntityBase) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *EntityBase) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EntityBase) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EntityBase) SetType(v string) {
	o.Type = v
}

func (o EntityBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *EntityBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityBase := _EntityBase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntityBase)

	if err != nil {
		return err
	}

	*o = EntityBase(varEntityBase)

	return err
}

type NullableEntityBase struct {
	value *EntityBase
	isSet bool
}

func (v NullableEntityBase) Get() *EntityBase {
	return v.value
}

func (v *NullableEntityBase) Set(val *EntityBase) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityBase) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityBase(val *EntityBase) *NullableEntityBase {
	return &NullableEntityBase{value: val, isSet: true}
}

func (v NullableEntityBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


