/*
SolarWinds Observability REST API

Testing EntitiesWebsitesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package swov1

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	swoclient "github.com/solarwinds/swo-sdk-go/swov1"
)

func Test_swov1_EntitiesWebsitesAPIService(t *testing.T) {

	configuration := swoclient.NewConfiguration()
	apiClient := swoclient.NewAPIClient(configuration)

	t.Run("Test EntitiesWebsitesAPIService EntitiesWebsitesEntityIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entityId string

		resp, httpRes, err := apiClient.EntitiesWebsitesAPI.EntitiesWebsitesEntityIdDelete(context.Background(), entityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitiesWebsitesAPIService EntitiesWebsitesEntityIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entityId string

		resp, httpRes, err := apiClient.EntitiesWebsitesAPI.EntitiesWebsitesEntityIdGet(context.Background(), entityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitiesWebsitesAPIService EntitiesWebsitesEntityIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entityId string

		resp, httpRes, err := apiClient.EntitiesWebsitesAPI.EntitiesWebsitesEntityIdPut(context.Background(), entityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitiesWebsitesAPIService EntitiesWebsitesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EntitiesWebsitesAPI.EntitiesWebsitesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
