// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/grepory/swo-sdk-go/swo/models/components"
)

type ListEntitiesRequest struct {
	// The entities type
	Type string `queryParam:"style=form,explode=false,name=type"`
	// The entities name
	Name *string `queryParam:"style=form,explode=false,name=name"`
	// Number of items in a response page
	PageSize *int `queryParam:"style=form,explode=false,name=pageSize"`
	// Token for the requested page
	SkipToken *string `queryParam:"style=form,explode=false,name=skipToken"`
}

func (o *ListEntitiesRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *ListEntitiesRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ListEntitiesRequest) GetPageSize() *int {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListEntitiesRequest) GetSkipToken() *string {
	if o == nil {
		return nil
	}
	return o.SkipToken
}

// ListEntitiesResponseBody - A JSON object containing an array of entities
type ListEntitiesResponseBody struct {
	Entities []components.Entity       `json:"entities"`
	PageInfo components.CommonPageInfo `json:"pageInfo"`
}

func (o *ListEntitiesResponseBody) GetEntities() []components.Entity {
	if o == nil {
		return []components.Entity{}
	}
	return o.Entities
}

func (o *ListEntitiesResponseBody) GetPageInfo() components.CommonPageInfo {
	if o == nil {
		return components.CommonPageInfo{}
	}
	return o.PageInfo
}

type ListEntitiesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A JSON object containing an array of entities
	Object *ListEntitiesResponseBody

	Next func() (*ListEntitiesResponse, error)
}

func (o *ListEntitiesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListEntitiesResponse) GetObject() *ListEntitiesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
