// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ChangeEventTags struct {
	AdditionalProp1 string `json:"additionalProp1"`
	AdditionalProp2 string `json:"additionalProp2"`
	AdditionalProp3 string `json:"additionalProp3"`
}

func (o *ChangeEventTags) GetAdditionalProp1() string {
	if o == nil {
		return ""
	}
	return o.AdditionalProp1
}

func (o *ChangeEventTags) GetAdditionalProp2() string {
	if o == nil {
		return ""
	}
	return o.AdditionalProp2
}

func (o *ChangeEventTags) GetAdditionalProp3() string {
	if o == nil {
		return ""
	}
	return o.AdditionalProp3
}
