// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ChangeEvent struct {
	ID            *int64           `json:"id,omitempty"`
	Name          string           `json:"name"`
	Title         string           `json:"title"`
	Timestamp     *int64           `json:"timestamp,omitempty"`
	Source        *string          `json:"source,omitempty"`
	Description   *string          `json:"description,omitempty"`
	ParentEventID *int64           `json:"parentEventId,omitempty"`
	Tags          *ChangeEventTags `json:"tags,omitempty"`
	Links         []CommonLink     `json:"links,omitempty"`
}

func (o *ChangeEvent) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ChangeEvent) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ChangeEvent) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *ChangeEvent) GetTimestamp() *int64 {
	if o == nil {
		return nil
	}
	return o.Timestamp
}

func (o *ChangeEvent) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *ChangeEvent) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ChangeEvent) GetParentEventID() *int64 {
	if o == nil {
		return nil
	}
	return o.ParentEventID
}

func (o *ChangeEvent) GetTags() *ChangeEventTags {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *ChangeEvent) GetLinks() []CommonLink {
	if o == nil {
		return nil
	}
	return o.Links
}
