// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CommonMetricInfo struct {
	Name             string `json:"name"`
	Units            string `json:"units"`
	Formula          string `json:"formula"`
	LastReportedTime string `json:"lastReportedTime"`
}

func (o *CommonMetricInfo) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CommonMetricInfo) GetUnits() string {
	if o == nil {
		return ""
	}
	return o.Units
}

func (o *CommonMetricInfo) GetFormula() string {
	if o == nil {
		return ""
	}
	return o.Formula
}

func (o *CommonMetricInfo) GetLastReportedTime() string {
	if o == nil {
		return ""
	}
	return o.LastReportedTime
}
