// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LogsArchive struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	DownloadURL       string `json:"downloadUrl"`
	ArchivedTimestamp string `json:"archivedTimestamp"`
	Severity          int64  `json:"severity"`
}

func (o *LogsArchive) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *LogsArchive) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *LogsArchive) GetDownloadURL() string {
	if o == nil {
		return ""
	}
	return o.DownloadURL
}

func (o *LogsArchive) GetArchivedTimestamp() string {
	if o == nil {
		return ""
	}
	return o.ArchivedTimestamp
}

func (o *LogsArchive) GetSeverity() int64 {
	if o == nil {
		return 0
	}
	return o.Severity
}
